name: Daily ApiCat Update

on:
  schedule:
    - cron: '0 20 * * *'   # 2 PM CDMX (UTC-6)
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Load .env variables
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
          echo "ENV_GITHUB_TOKEN=${{ secrets.ENV_GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
          echo "USER_EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "ENV_GITHUB_REPO=${{ secrets.ENV_GITHUB_REPO }}" >> $GITHUB_ENV

      - name: Run TheCatApi PHP Script
        run: php TheCatApi.php
